### PR TITLE
DNN-9099: update skin pane selector.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by tpluscode** [comment]
Oh,`ModuleDialog.js` and `ModuleManager.js` are so similar with those of Dnn.Evoq.Basic? Did they start as copies of one another?

**Comment by zyhfish** [comment]
PR in evoq.basic already submit with similar changes, Dnn.EditBar are copied from Evoq but only available in platform.

**Comment by tpluscode** [comment]
It's nothing we will do about this now, but I dislike how that much code could have been reused instead of copied :(

**Comment by tpluscode** [comment]
fixed #22

**Pull request merged**
