### PR TITLE
Migrate from packages.config to PackageReference

### PR DESCRIPTION
**Pull request by bdukes**
@ohine this fixes the NuGet versioning issue we saw (for this project).  Assuming there aren't any other issues getting this merged, I can make this same change in the other repos.

### CODE REVIEW

**Comment by bdukes** [comment]
This did successfully pass the build: https://dotnetfoundation.visualstudio.com/DNN/_build/results?buildId=3372.  By converting to version ranges, the build now pulls version 9.2.0.366 of the _DotNetNuke_ NuGet packages

**Review by ohine — APPROVED** [review]
@bdukes Thanks for taking the time to track down a fix for this! This looks great to me! 

My only comment/question is can we use 9.2.0^ instead of having to call out each version with each new release?

**Comment by bdukes** [comment]
I don't think that syntax is supported (see https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards), but we can do `9.2.*`.  Using the wildcard syntax will also include pre-release versions, so we can start publishing NuGet packages with versions like `9.2.1.123-alpha` and this will pick it up (while not polluting the NuGet server with multiple "production" releases for 9.2.1)

**Comment by bdukes** [comment]
However, when switched to `9.2.*`, I start pulling in DNN `9.2.2.14`.  So, we would need to switch back to `[9.2.0,9.2.1)` when we create a release branch (which sounds like something we'd forget to do, without some sort of automation around release prep).

**Comment by ohine** [comment]
@bdukes I think this is all set already in the combined repo. Can you verify and close or resubmit the issue against that repo? thanks!

**Pull request closed without merging**
